### ISSUE TITLE
Doorbell notifications

### ISSUE THREAD

**Issue by sharksfan09** [Sunoo/homebridge-smtp-motion#110]
Is there anyway to trigger the camera-ffmpeg doorbell notifications?

**Comment by Sunoo** [comment]
You can do that over [HTTP](https://sunoo.github.io/homebridge-camera-ffmpeg/automation/http.html) or [MQTT](https://sunoo.github.io/homebridge-camera-ffmpeg/automation/mqtt.html).

**Comment by Sunoo** [comment]
Sorry, didn't notice which project this issue was open on.

Why are you trying to activate doorbell via SMTP? Is it just to make motion alerts display on Apple TV?

**Comment by sharksfan09** [comment]
Correct, I would like to have motion detection alerts show up on the Apple TV from my REOlink camera. I have found that the person detection is actually quite good and does not provide a lot of false positives. Having that alert show up on the AppleTV when someone walks up to the front door would be nice.

**Comment by Sunoo** [comment]
Okay, in that case, I plan to add a setting to homebridge-camera-ffmpeg to process motion alerts as doorbell presses soon. It makes more sense to add there instead of here anyways.

It's going to be part of a decent rework of the way motion and doorbells are handled, but I'm hoping to have it done in the next few weeks.

**Comment by sharksfan09** [comment]
That will be great! I will keep my eyes out for that, thank you for all your hard work on this.

**Comment by Sunoo** [comment]
This was added in homebridge-camera-ffmpeg v3.0.6. I decided I could sneak this in before the massive overhaul.
