### ISSUE TITLE
Email received, but no home app notification

### ISSUE THREAD

**Issue by hassanmah** [Sunoo/homebridge-smtp-motion#98]
Hey,

I followed your guide and manage to get the following in the logs: `[19/01/2021, 13:35:18] [smtpMotion] [Door] Email received.`

Only issue is I don't get home app notifications. I'm sending the email to Door@cctv.com

My config file is like this:

```
{
   "platform": "smtpMotion",
   "smtp_port": 2525,
   "http_port": 8581
},
{
   "name": "Camera FFmpeg",
    "cameras": [
        {
          "name": "Door",
           "manufacturer": "Reolink",
           "model": "RLC-410",
           "motion": true,
         }
      ]
}
```

Thanks

**Comment by Sunoo** [comment]
Do you have alerts set up in the Home app? They’re off by default.

**Comment by hassanmah** [comment]
Yes see attached 
![IMG_4813EEC270EC-1](https://user-images.githubusercontent.com/3025707/105042446-2ccc2700-5a5c-11eb-8a9d-27bb3bcdcfbc.jpeg)

**Comment by Sunoo** [comment]
I just noticed I don’t see the HTTP port set in your Camera FFmpeg config, if that’s actually missing you’ll need to add it.

**Comment by hassanmah** [comment]
That worked thanks, can we not attach a image to the notification too?

**Comment by Sunoo** [comment]
Snapshots should be included in the notification if your camera responds to the request fast enough. If there is a way to get a still image directly from the camera, you can add it in `stillImageSource`, and that usually works. Otherwise it has to grab an image from the video stream, which often takes longer than iOS will wait before showing the notification.
